name: Code styles, tests and building
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
    - run: node dist/src/index.js       
    - run: tsc -p ./tsconfig.build.json       
    - run: npx eslint -c .eslintrc.json .//*.{ts,test.ts}       
    - run: npx prettier -c .//*.{ts,test.ts}       
    - run: npx jest --config=jest.config.ts
    env:
      CI: true