name: Code styles, tests and building
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
    - run: node dist/src/index.js       
    - run: tsc -p ./tsconfig.build.json       
    - run: npx eslint -c .eslintrc.json .//*.{ts,test.ts}       
    - run: npx prettier -c .//*.{ts,test.ts}       
    - run: npx jest --config=jest.config.ts
    env:
      CI: true

      "scripts": {
    "test": "npx jest --config=jest.config.ts",
    "test:watch": "npx jest --watch --config=jest.config.ts",
    "dev": "ts-node-dev -r tsconfig-paths/register src/index.ts",
    "start": "node dist/src/index.js",
    "start:dev": "ts-node src/index.ts",
    "start:dev:log": "DEBUG=db-inclui:* ts-node src/index.ts",
    "build": "tsc -p ./tsconfig.build.json",
    "lint:check": "npx eslint -c .eslintrc.json ./**/*.{ts,test.ts}",
    "lint:fix": "npx eslint -c .eslintrc.json --fix ./**/*.{ts,test.ts}",
    "prettier:check": "npx prettier -c ./**/*.{ts,test.ts}",
    "prettier:write": "npx prettier -w ./**/*.{ts,test.ts}"
  }
